/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java project to get you started.
 * For more details take a look at the Java Quickstart chapter in the Gradle
 * User Manual available at https://docs.gradle.org/5.3.1/userguide/tutorial_java_projects.html
 */

plugins {
    // Apply the java plugin to add support for Java
    id("java")

    // Apply the application plugin to add support for building an application
    id("application")

    //id 'com.github.johnrengelman.shadow' version '6.0.0' // only for Gradle 6+
}

dependencies {
    implementation("net.dv8tion:JDA:5.0.0-beta.6")
    implementation("com.google.cloud:google-cloud-translate:1.88.0")
    implementation("com.github.Walkyst:lavaplayer-fork:1.3.96")
    //implementation 'com.sedmelluq:lavaplayer-natives-extra:1.3.13' // only for ARM
    implementation("ch.qos.logback:logback-classic:1.2.3")

    implementation("com.github.Doomsdayrs:Jikan4java:v1.4.2")
    implementation("org.json:json:20210307")
    implementation("org.apache.commons:commons-lang3:3.12.0")
    implementation("net.lingala.zip4j:zip4j:2.8.0")

}

repositories {
    maven(url = "https://m2.dv8tion.net/releases")
    maven(url = "https://dl.bintray.com/sedmelluq/com.sedmelluq")
    maven(url = "https://jitpack.io")
    mavenCentral()
}

application {
    // Define the main class for the application.
    mainClass.set("bot.App")
}

tasks.withType(JavaCompile::class) {
    options.encoding = "UTF-8"
}
