version: '3.7'
services:
  ciabattabot:
    image: ciabattabot:latest
    build:
      dockerfile: Dockerfile
      context: .
      args:
        - "CIABATTA_BOT_COMMAND_PREFIX=$CIABATTA_BOT_COMMAND_PREFIX"
        - "CIABATTA_BOT_DISCORD_BOT_TOKEN=$CIABATTA_BOT_DISCORD_BOT_TOKEN"
        - "CIABATTA_BOT_PO_TOKEN=$CIABATTA_BOT_PO_TOKEN"
        - "CIABATTA_BOT_PO_VISITOR_DATA=$CIABATTA_BOT_PO_VISITOR_DATA"
    environment:
      JAVA_OPTS: "-Xmx512m"
      CIABATTA_BOT_COMMAND_PREFIX:
      CIABATTA_BOT_DISCORD_BOT_TOKEN:
      CIABATTA_BOT_PO_TOKEN:
      CIABATTA_BOT_PO_VISITOR_DATA:
